name: inception

services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb:0.1
    container_name: mariadb
    env_file: .env
    secrets:
      - mariadb_root_pass
      - mariadb_admin_pass
      - mariadb_wp_user_pass
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - backend
    restart: always
    healthcheck:
      test: [
        "CMD", "mariadb-admin", "ping", "-h", "localhost", 
        "-u", "healthcheck", "-phealth_password"
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      
      # docker exec -it mariadb mysql -u root -p -e "SHOW DATABASES;"
      # docker exec -it mariadb mysql -u root -p -e "SELECT User, Host FROM mysql.user;"
  
  wordpress:
    build: ./requirements/wordpress
    image: wordpress:0.1
    container_name: wordpress
    env_file: .env
    secrets:
      - mariadb_wp_user_pass
      - wp_admin_pass
      - wp_user_pass
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - backend
    restart: always
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "timeout 2s bash -c '</dev/tcp/127.0.0.1/9000' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  nginx:
    build: ./requirements/nginx
    image: nginx:0.1
    container_name: nginx
    env_file: .env
    ports:
      - "443:443"
    secrets:
      - nginx_cert
      - nginx_key
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - backend
    restart: always
    depends_on:
      wordpress:
        condition: service_healthy
      adminer:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://127.0.0.1:443"]
      interval: 10s
      timeout: 5s
      retries: 3
  
  redis:
    build: ./requirements/bonus/redis
    image: redis:0.1
    container_name: redis
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s
  
  adminer:
    build: ./requirements/bonus/adminer
    image: adminer:0.1
    container_name: adminer
    restart: always
    networks:
      - backend
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "timeout 2s bash -c '</dev/tcp/127.0.0.1/9000' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  ftp_server:
    build: ./requirements/bonus/ftp_server
    image: ftp_server:0.1
    container_name: ftp_server
    restart: always
    env_file: .env
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - backend
    secrets:
      - ftp_password
    depends_on:
      wordpress:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "ftp -n localhost <<< quit || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER_LOG:-${SUDO_USER:-$USER}}/data/mariadb

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER_LOG:-${SUDO_USER:-$USER}}/data/wordpress

  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER_LOG:-${SUDO_USER:-$USER}}/data/redis


networks:
  backend:
    driver: bridge

secrets:
  mariadb_root_pass:
    file: ${MARIADB_ROOT_PASSWORD_HOST_FILE}
  mariadb_admin_pass:
    file: ${MARIADB_ADMIN_PASSWORD_HOST_FILE}
  mariadb_wp_user_pass:
    file: ${MARIADB_WP_USER_PASSWORD_HOST_FILE}
  
  wp_admin_pass:
    file: ${WP_ADMIN_PASSWORD_HOST_FILE}
  wp_user_pass:
    file: ${WP_USER_PASSWORD_HOST_FILE}
  
  nginx_cert:
    file: ${NGINX_SSL_CERTIFICATE_HOST_FILE}
  nginx_key:
    file: ${NGINX_SSL_CERTIFICATE_KEY_HOST_FILE}

  ftp_password:
    file: ${FTP_PASSWORD_HOST_FILE}

