name: inception

# ==============================================================================
# 1. TEMPLATES AND ANCHORS
# ==============================================================================
x-common-service: &common-service
  init: true
  restart: always
  networks:
    - backend

# ==============================================================================
# 2. SERVICES
# ==============================================================================
services:
  mariadb:
    <<: *common-service
    build: ./requirements/mariadb
    image: mariadb:0.1
    container_name: mariadb
    environment:
      - MARIADB_DATABASE
      - MARIADB_ADMIN_USER
      - MARIADB_WP_USER
      - MARIADB_ROOT_PASSWORD_FILE
      - MARIADB_ADMIN_PASSWORD_FILE
      - MARIADB_WP_USER_PASSWORD_FILE
    secrets:
      - mariadb_root_pass
      - mariadb_admin_pass
      - mariadb_wp_user_pass
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: [
        "CMD",
        "mariadb-admin",
        "--protocol=socket",
        "-S", "/run/mysqld/mysqld.sock",
        "-u", "healthcheck",
        "-phealthcheck_pass",
        "ping"
      ]
      interval: 10s
      timeout: 5s
      retries: 3
  
  wordpress:
    <<: *common-service
    build: ./requirements/wordpress
    image: wordpress:0.1
    container_name: wordpress
    environment:
      - DOMAIN_NAME
      - WP_DB_NAME
      - WP_DB_USER
      - WP_DB_HOST
      - WP_DB_PASSWORD_FILE
      - WP_ADMIN_USER
      - WP_ADMIN_EMAIL
      - WP_USER
      - WP_USER_EMAIL
      - WP_ADMIN_PASSWORD_FILE
      - WP_USER_PASSWORD_FILE
      - WP_TITLE
      - WP_REDIS_HOST
      - WP_REDIS_PORT
    secrets:
      - mariadb_wp_user_pass
      - wp_admin_pass
      - wp_user_pass
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "timeout 2s bash -c '</dev/tcp/127.0.0.1/9000' &&
                timeout 3s wp db check --allow-root || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  nginx:
    <<: *common-service
    build: ./requirements/nginx
    image: nginx:0.1
    container_name: nginx
    ports:
      - "443:443"
    secrets:
      - source: nginx_cert
        target: /etc/nginx/ssl/inception.crt
        mode: 0444
      - source: nginx_key
        target: /etc/nginx/ssl/inception.key
        mode: 0400
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      wordpress:
        condition: service_healthy
      adminer:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://127.0.0.1:443"]
      interval: 10s
      timeout: 5s
      retries: 3
  
  redis:
    <<: *common-service
    build: ./requirements/bonus/redis
    image: redis:0.1
    container_name: redis
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s

  portainer:
    <<: *common-service
    build: ./requirements/bonus/portainer
    image: portainer:0.1
    container_name: portainer
    environment:
      - PORTAINER_PASSWORD_FILE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    secrets:
      - portainer_admin_pass

  adminer:
    <<: *common-service
    build: ./requirements/bonus/adminer
    image: adminer:0.1
    container_name: adminer
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "timeout 2s bash -c '</dev/tcp/127.0.0.1/9000' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  ftp_server:
    <<: *common-service
    build: ./requirements/bonus/ftp_server
    image: ftp_server:0.1
    container_name: ftp_server
    environment:
      - DOMAIN_NAME
      - FTP_USER
      - FTP_PASSWORD_FILE
    ports:
      - "21:21"
      - "21210-21220:21210-21220"
    volumes:
      - wordpress_data:/var/www/html
    secrets:
      - ftp_password
    depends_on:
      wordpress:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "pgrep vsftpd || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  my-website:
    <<: *common-service
    build: ./requirements/bonus/my-website
    image: my-website:0.1
    container_name: my-website

# ==============================================================================
# 3. VOLUMES
# ==============================================================================
volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH}/mariadb

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH}/wordpress

  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH}/redis

  portainer_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH}/portainer

# ==============================================================================
# 4. NETWORKS
# ==============================================================================
networks:
  backend:
    driver: bridge

# ==============================================================================
# 5. SECRETS
# ==============================================================================
secrets:
  mariadb_root_pass:
    file: ${MARIADB_ROOT_PASSWORD_HOST_FILE}
  mariadb_admin_pass:
    file: ${MARIADB_ADMIN_PASSWORD_HOST_FILE}
  mariadb_wp_user_pass:
    file: ${MARIADB_WP_USER_PASSWORD_HOST_FILE}
  
  wp_admin_pass:
    file: ${WP_ADMIN_PASSWORD_HOST_FILE}
  wp_user_pass:
    file: ${WP_USER_PASSWORD_HOST_FILE}
  
  nginx_cert:
    file: ${NGINX_SSL_CERTIFICATE_HOST_FILE}
  nginx_key:
    file: ${NGINX_SSL_CERTIFICATE_KEY_HOST_FILE}

  ftp_password:
    file: ${FTP_PASSWORD_HOST_FILE}

  portainer_admin_pass:
    file: ${PORTAINER_PASSWORD_HOST_FILE}

