FROM debian:bookworm

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    nginx \
    openssl \
    curl && \
    rm -rf /var/lib/apt/lists/*


COPY conf/nginx.conf /etc/nginx/nginx.conf
COPY tools/docker-entrypoint.sh /usr/local/bin/

RUN chmod +x /usr/local/bin/docker-entrypoint.sh

EXPOSE 443

ENTRYPOINT ["docker-entrypoint.sh"]
