USE mysql;
FLUSH PRIVILEGES;

ALTER USER 'root'@'localhost' IDENTIFIED BY '${MYSQL_ROOT_PASSWORD}';

CREATE USER IF NOT EXISTS '${MARIADB_ADMIN_USER}'@'%'
IDENTIFIED BY '${MYSQL_ADMIN_PASSWORD}';

GRANT ALL PRIVILEGES
ON *.* TO '${MARIADB_ADMIN_USER}'@'%'
WITH GRANT OPTION;

CREATE DATABASE IF NOT EXISTS `${MARIADB_DATABASE}`;

CREATE USER IF NOT EXISTS '${MARIADB_WP_USER}'@'%'
IDENTIFIED BY '${MARIADB_WP_USER_PASSWORD}';

GRANT ALL PRIVILEGES 
ON `${MARIADB_DATABASE}`.* TO '${MARIADB_WP_USER}'@'%';

CREATE USER IF NOT EXISTS 'healthcheck'@'localhost' 
IDENTIFIED VIA unix_socket AS 'root';

GRANT USAGE ON *.* TO 'healthcheck'@'localhost';

DROP DATABASE IF EXISTS test;
DROP USER IF EXISTS ''@'localhost';
DROP USER IF EXISTS ''@'${HOSTNAME}';

REVOKE ALL PRIVILEGES ON `test`.* FROM PUBLIC;
REVOKE ALL PRIVILEGES ON `test\_%`.* FROM PUBLIC;

FLUSH PRIVILEGES;
